language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

env:
  - DJANGO=Django==1.3.5
  - DJANGO=Django==1.4.3
  #latest development environment
  - DJANGO=https://github.com/django/django/archive/master.tar.gz

matrix:
  allow_failures:
    # Django 1.5a1 is still buggy so it's okay to fail
    # Still; if it works, that's nice to know!
    #- env: DJANGO=https://www.djangoproject.com/download/1.5b2/tarball/

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install -q https://github.com/praekelt/django-setuptest/archive/f4eacb4a929cdcc853a5c053c282dada5bdedc99.tar.gz --use-mirrors

# command to run tests
script: python setup.py test
