language: python
python:
  - "2.7"
  - "nightly"

env:
  - DJANGO=Django==1.8.2
  #latest development environment
  - DJANGO=https://github.com/django/django/archive/master.tar.gz

matrix:
  allow_failures:
    # Django 1.5a1 is still buggy so it's okay to fail
    # Still; if it works, that's nice to know!
    #- env: DJANGO=https://www.djangoproject.com/download/1.5b2/tarball/

# command to install dependencies
install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
# command to run tests
script: python manage.py test
