language: python
python:
  - "2.7"
  - "nightly"

env:
  - DJANGO=Django==1.8.2
  #latest development environment
  - DJANGO=https://github.com/django/django/archive/master.tar.gz

# command to install dependencies
install:
  - pip install -q $DJANGO
  - pip install -r requirements.txt
# command to run tests
script: python manage.py test
