language: python
<<<<<<< HEAD
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
# script: nosetests
=======

python:
  # django-setuptests 0.1.2 bugs on Python 2.5 - fixed in next release
  # - "2.5"
  - "2.6"
  - "2.7"

env:
  - DJANGO=Django==1.3.4
  - DJANGO=Django==1.4.2
  - DJANGO=https://www.djangoproject.com/download/1.5a1/tarball/

matrix:
  allow_failures:
    # Django 1.5a1 is still buggy so it's okay to fail
    # Still; if it works, that's nice to know!
    - env: DJANGO=https://www.djangoproject.com/download/1.5a1/tarball/

# command to install dependencies
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script: python setup.py test
>>>>>>> 7e96de8... Run setup.py test under Travis.
